---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: river-dev
bases:
  - ../automated

patchesStrategicMerge:
  - river-data-patch.yaml
  - ingress-patch.yaml
  - gitrepo-patch.yaml
