---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: river-data-auto-update
  namespace: river-data
spec:
  git:
    checkout:
      ref:
        branch: deploy
    commit:
      author:
        email: yebyen+fluxcd@gmail.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: deploy
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: river-data-rw
  update:
    path: ./deploy/
    strategy: Setters
